name: Build Container Image From Pull Request
description: Build and publish container image
inputs:
  registry:
    description: Hostname (not URL) of image registry
    required: true
  registry_repo: 
    description: Project/component of image, i.e. cms/admin
    required: true
  registry_user:
    description: Username for registry auth
    required: true
  registry_pass:
    description: Password for registry auth
outputs:
  version:
    description: 'Version of image'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.meta.outputs.version }}
runs:
  using: 'composite'
  steps:
  - name: Get short SHA of commit for image tagging
    id: sha7
    run: echo "sha7=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
    shell: bash

  - name: Login to registry
    uses: docker/login-action@v3
    with:
      username: ${{ inputs.registry_user }}
      password: ${{ inputs.registry_pass }}
      registry: ${{ inputs.registry }}

  - name: Extract metadata (tags, labels) for Docker
    # because this is happening on a PR event, the label will be pr-##
    id: meta
    uses: docker/metadata-action@v5
    with:
      images: |
        ${{ inputs.registry }}/${{ inputs.registry_repo }}
      tags: |
        type=ref,suffix=-${{ steps.sha7.outputs.sha7 }},event=pr
      flavor: |
        latest=false

  - name: Setup Docker Buildx
    id: setup_docker_buildx
    uses: docker/setup-buildx-action@v3
    with:
      buildkitd-config-inline: |
        [registry."${{ inputs.registry }}"]
          http = false
          insecure = false
          ca=["/etc/ssl/certs/ca-certificates.crt"]

  - name: Build and push images to registry
    uses: docker/build-push-action@v5
    with:
      context: ./
      file: Dockerfile
      push: true
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
